services:
  - type: web
    name: deepfake-detection-backend
    rootDir: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"

staticSites:
  - name: deepfake-detection-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
